import Image from 'next/image';
import { createInstance } from 'i18next';
import { getLocale } from '@/lib/locale';
import { en, de } from '@/lib/translations';
import { ShaderBackground } from '@/components/ui/blue-halftone';
import { ScrollReveal } from '@/components/scroll-reveal';
import { BookingCalendar } from '@/components/booking-calendar';
import { ArrowUp, ArrowUpRight, Award, Bot, BriefcaseBusiness, GraduationCap, Languages, Mail, MapPin } from 'lucide-react';
export default async function Page(){
 const locale=await getLocale();
 const i18n=createInstance();
 await i18n.init({lng:locale,fallbackLng:'en',resources:{en:{translation:en},de:{translation:de}},interpolation:{escapeValue:false}});
 const t=i18n.t.bind(i18n);
 const calLink=(process.env.CAL_LINK??'').trim().replace(/^\/+|\/+$/g,'');
 const bookingUrl=calLink ? `https://cal.com/${calLink}` : 'mailto:mail@simon-paul.com';
const jobs=[
{date:t('now'),name:'Arctis AI',role:'founding',desc:'arctis',city:'munich',logo:'arctis.webp',href:'https://arctisai.com/'},
{date:'03 — 08 / 2025',name:t('coachOrg'),role:'coachRole',desc:'coach',city:'munich',logo:'personio-dark.svg',extraLogo:'csee.svg',extraName:'CSEE',href:'https://www.personio.com/',extraHref:'https://csee.tech/'},
{date:'04 — 09 / 2024',name:'fortiss',role:'graphRole',desc:'graph',city:'munich',logo:'fortiss.png',href:'https://www.fortiss.org/'},
{date:'08 — 10 / 2023',name:'Snowflake',role:'intern',desc:'snow',city:'berlin',logo:'snowflake-white.png',href:'https://www.snowflake.com/'},
{date:'08 / 2022 — 02 / 2023',name:'Amazon Web Services',role:'intern',desc:'aws',city:'dublin',logo:'aws-dark.svg',href:'https://aws.amazon.com/'},
{date:'03 — 04 / 2021',name:'TNG Technology Consulting',role:'tngRole',desc:'tng',city:'munich',logo:'tng.svg',href:'https://www.tngtech.com/'}
];return <>
<a className="skip" href="#main">{t('skip')}</a><div className="background"><ShaderBackground/><ScrollReveal/></div>
<header id="top"><a className="wordmark" href="#top">Simon Paul</a><div className="languages" role="group" aria-label={t('language')}><Languages className="language-icon" aria-hidden="true"/>{['en','de'].map(l=><a key={l} href={`/language?locale=${l}`} aria-current={locale===l?'true':undefined} lang={l}>{l.toUpperCase()}</a>)}</div></header>
<main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow hero-role"><Bot aria-hidden="true"/>{t('role')}<span className="role-divider">/</span><MapPin aria-hidden="true"/>{t('munich')}</p><h1>{t('hello')}</h1><p className="hero-tagline">{t('tagline')}</p><p className="intro">{t('intro')}</p><a className="hero-honour" href="#education"><Award aria-hidden="true"/><span><strong>{t('topClass')}</strong><small>{t('rank')}</small></span></a><div className="hero-actions"><a className="button" href={bookingUrl} target="_blank" rel="noreferrer"><span className="action-label">{t('chat')}</span><span className="action-arrow"><ArrowUpRight aria-hidden="true"/></span></a><a className="social-link" href="https://www.linkedin.com/in/simon-paul1/" target="_blank" rel="noreferrer"><span className="action-label">LinkedIn</span><span className="action-arrow"><ArrowUpRight aria-hidden="true"/></span></a></div></div><div className="portrait-wrap"><Image className="portrait" src="/simon-cutout.webp" alt={t('portrait')} width={1254} height={1254} sizes="(max-width: 700px) 340px, (max-width: 1320px) 42vw, 530px" preload quality={85}/></div></section>
<div className="affiliations"><div className="company-icons"><img className="strip-arctis" src="/logos/arctis.webp" alt="Arctis AI"/><img className="strip-snowflake" src="/logos/snowflake-white.png" alt="Snowflake"/><span className="strip-aws"><img src="/logos/aws-dark.svg" alt="AWS"/></span><img className="strip-tum" src="/logos/tum.svg" alt="TUM"/></div></div>
<section className="section"><p className="eyebrow section-label"><BriefcaseBusiness aria-hidden="true"/>{t('workLabel')}</p><h2>{t('work')}</h2><div className="timeline">{jobs.map(job=><article className={`job${job.extraHref ? ' paired-job' : ''}`} key={job.name}><div className="job-meta"><span className="date">{job.date}</span><span className="job-city"><MapPin aria-hidden="true"/>{t(job.city)}</span></div><div className="job-identity"><div className={`organization-logos${job.extraLogo ? ' paired' : ''}`}><span className={`company-logo logo-${job.logo.split('.')[0]}`}>{job.href ? <a href={job.href} target="_blank" rel="noreferrer" aria-label={job.name}><img src={`/logos/${job.logo}`} alt="" aria-hidden="true"/></a> : <img src={`/logos/${job.logo}`} alt="" aria-hidden="true"/>}</span>{job.extraLogo && <span className={`company-logo companion-logo logo-${job.extraLogo.split('.')[0]}`}><img src={`/logos/${job.extraLogo}`} alt={job.extraName}/></span>}</div><div><h3>{job.name}</h3><p className="job-role">{t(job.role)}</p></div></div><p>{t(job.desc)}</p><div className="entry-links">{job.extraHref && <a href={job.extraHref} target="_blank" rel="noreferrer" aria-label={t('visit',{name:'CSEE'})} title="CSEE"><span>CSEE</span><ArrowUpRight aria-hidden="true"/></a>}<a href={job.href} target="_blank" rel="noreferrer" aria-label={t('visit',{name:job.extraHref?'Personio':job.name})} title={job.extraHref?'Personio':job.name}><span>{job.extraHref?'Personio':job.name}</span><ArrowUpRight aria-hidden="true"/></a></div></article>)}</div></section>
<section className="section education-section" id="education"><p className="eyebrow section-label"><GraduationCap aria-hidden="true"/>{t('educationLabel')}</p><div className="education-cards"><article><div className="entry-links"><a href="https://www.tum.de/" target="_blank" rel="noreferrer" aria-label={t('visit',{name:t('tum')})}><span>TUM</span><ArrowUpRight aria-hidden="true"/></a></div><img className="education-logo tum-logo" src="/logos/tum.svg" alt="" aria-hidden="true"/><div><p className="education-date">2020 — 2026 · {t('munich')}</p><h3>{t('tum')}</h3><p className="education-role">{t('tumRole')}</p><p>{t('tumText')}</p><div className="academic-highlight"><span className="rank-number">#1</span><div><strong>{t('topClass')}</strong><p>{t('rankDetail')}</p><span>{t('excellence')}</span><span>{t('scholarship')}</span></div></div></div></article><article><div className="entry-links"><a href="https://www.kth.se/" target="_blank" rel="noreferrer" aria-label={t('visit',{name:t('kth')})}><span>KTH</span><ArrowUpRight aria-hidden="true"/></a></div><img className="education-logo kth-logo" src="/logos/kth.svg" alt="" aria-hidden="true"/><div><p className="education-date">08 / 2025 — 01 / 2026 · {t('stockholm')}</p><h3>{t('kth')}</h3><p className="education-role">{t('kthRole')}</p><p>{t('kthText')}</p></div></article></div></section>
<section className="contact booking-section" id="book"><p className="eyebrow">{t('contact')}</p><h2>{t(calLink?'booking':'chat')}</h2>{calLink && <div className="calendar-embed"><BookingCalendar calLink={calLink} locale={locale}/></div>}<div className="booking-alternatives"><a href="mailto:mail@simon-paul.com"><Mail aria-hidden="true"/>mail@simon-paul.com</a></div></section></main><footer><span>© {new Date().getFullYear()} Simon Paul</span><span className="footer-location"><MapPin aria-hidden="true"/>{t('location')}</span><a href="#top">{t('back')}<ArrowUp aria-hidden="true"/></a></footer></>}
