'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
const calLink=(process.env.NEXT_PUBLIC_CAL_LINK ?? '').trim().replace(/^\/+|\/+$/g,'');
const bookingUrl=calLink ? `https://cal.com/${calLink}` : 'mailto:mail@simon-paul.com';
const BookingCalendar=dynamic(()=>import('@calcom/embed-react'),{ssr:false});
import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next, I18nextProvider, useTranslation } from 'react-i18next';
import { ShaderBackground } from '@/components/ui/blue-halftone';
import { ArrowUp, ArrowUpRight, Award, Bot, BriefcaseBusiness, GraduationCap, Languages, Mail, MapPin } from 'lucide-react';
const en = {
booking:'Book a 30-minute chat',visit:'Visit {{name}} website',role:'AI ENGINEER',hello:'Hi, I’m Simon.',tagline:'I build AI agents that turn complex information into meaningful action.',intro:'Founding Engineer & Head of Engineering at Arctis AI.',chat:'Let’s chat',before:'EXPERIENCE',work:'Where I’ve made an impact.',workLabel:'EXPERIENCE & RESEARCH',now:'JAN 2026 — NOW',arctis:'Backed by EWOR, raised $1M+. Employee #1. Built AI agents that find, analyze, and package construction tenders, and compare construction bids.',snow:'Built a gRPC interceptor to protect database transactions in systems handling 100k+ requests per second.',aws:'Automated Aurora Data Lake operations, saving up to two hours per procedure. Added monitoring and presented the solution to 19 global teams.',intern:'Software Development Engineer Intern',founding:'Founding Engineer & Head of Engineering',coachRole:'CoachAI · Project Team Co-Lead',coachOrg:'CSEE × Personio',coach:'Co-led a five-person team building AI voice coaching for HR, spanning architecture, full-stack integration, and real-time communication feedback.',graphRole:'Bachelor’s Thesis · Graph RAG',graph:'Built an agent-based RAG system that generates SPARQL queries for knowledge graphs, improving accuracy on advanced questions.',tngRole:'Junior Consultant · Internship',tng:'Worked on image recognition, processing, and comparison to detect order-picking errors for a pharmaceutical wholesaler, using OpenCV and NumPy.',educationLabel:'EDUCATION',tum:'Technical University of Munich',tumRole:'B.Sc. & M.Sc. Information Systems',tumText:'Focus on computer science and AI. Tutored software engineering and created programming exercises used by 1,000+ students annually.',rank:'#1 of 115 · Summer 2025',topClass:'Top of class at TUM',rankDetail:'Ranked 1st out of 115 students · Summer 2025',excellence:'best.in.tum · Top 2% of TUM',scholarship:'Deutschlandstipendium scholar',kth:'KTH Royal Institute of Technology',kthRole:'Exchange Semester',kthText:'A semester in Stockholm as part of my master’s at TUM.',contact:'Have an interesting problem?',location:'Munich, Germany',munich:'Munich',berlin:'Berlin',dublin:'Dublin',stockholm:'Stockholm',skip:'Skip to content',language:'Choose language',portrait:'Simon Paul',back:'Back to top'
};
const de: typeof en = {
booking:'30 Minuten zum Kennenlernen',visit:'Website von {{name}} besuchen',role:'AI ENGINEER',hello:'Hi, ich bin Simon.',tagline:'Ich baue KI-Agenten, die komplexe Informationen in konkrete Schritte umsetzen.',intro:'Founding Engineer & Head of Engineering bei Arctis AI.',chat:'Lass uns sprechen',before:'ERFAHRUNG',work:'Wo ich etwas bewegt habe.',workLabel:'ERFAHRUNG & FORSCHUNG',now:'JAN. 2026 — HEUTE',arctis:'Unterstützt von EWOR, über 1 Mio. US-Dollar eingesammelt. Mitarbeiter Nr. 1. KI-Agenten entwickelt, die Bauausschreibungen finden, analysieren und aufbereiten sowie Bauangebote vergleichen.',snow:'Einen gRPC-Interceptor entwickelt, der Datenbanktransaktionen in Systemen mit über 100.000 Anfragen pro Sekunde schützt.',aws:'Abläufe für Aurora Data Lake automatisiert und bis zu zwei Stunden pro Vorgang eingespart. Monitoring ergänzt und die Lösung 19 globalen Teams vorgestellt.',intern:'Software Development Engineer · Praktikum',founding:'Founding Engineer & Head of Engineering',coachRole:'CoachAI · Co-Leitung des Projektteams',coachOrg:'CSEE × Personio',coach:'Ein fünfköpfiges Team beim Bau eines KI-Sprachcoaches für HR mitgeleitet – von Architektur und Full-Stack-Integration bis zu Echtzeit-Feedback zur Kommunikation.',graphRole:'Bachelorarbeit · Graph RAG',graph:'Ein agentenbasiertes RAG-System entwickelt, das SPARQL-Abfragen für Wissensgraphen erzeugt und komplexe Fragen genauer beantwortet.',tngRole:'Junior Consultant · Praktikum',tng:'An Bilderkennung, Bildverarbeitung und Bildvergleich gearbeitet, um Kommissionierfehler im Pharmagroßhandel zu erkennen – mit OpenCV und NumPy.',educationLabel:'STUDIUM',tum:'Technische Universität München',tumRole:'B.Sc. & M.Sc. Wirtschaftsinformatik',tumText:'Schwerpunkte Informatik und KI. Software-Engineering-Tutorien betreut und Programmieraufgaben für jährlich über 1.000 Studierende erstellt.',rank:'Platz 1 von 115 · Sommer 2025',topClass:'Jahrgangsbester an der TUM',rankDetail:'Platz 1 von 115 Studierenden · Sommer 2025',excellence:'best.in.tum · Top 2 % der TUM',scholarship:'Deutschlandstipendium',kth:'KTH Royal Institute of Technology',kthRole:'Auslandssemester',kthText:'Ein Semester in Stockholm im Rahmen meines Masterstudiums an der TUM.',contact:'Ein spannendes Problem im Kopf?',location:'München, Deutschland',munich:'München',berlin:'Berlin',dublin:'Dublin',stockholm:'Stockholm',skip:'Zum Inhalt springen',language:'Sprache wählen',portrait:'Simon Paul',back:'Nach oben'
};
function Profile(){const {t,i18n}=useTranslation();
useEffect(()=>{
 if(!('IntersectionObserver' in window) || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
 const entries=document.querySelectorAll<HTMLElement>('.job, .education-cards article');
 const observer=new IntersectionObserver(changes=>{
  changes.forEach(({isIntersecting,target})=>{
   if(isIntersecting){(target as HTMLElement).dataset.reveal='visible';observer.unobserve(target)}
  });
 },{threshold:0.08,rootMargin:'0px 0px -24px 0px'});
 entries.forEach(entry=>{
  if(entry.getBoundingClientRect().top>=window.innerHeight){entry.dataset.reveal='pending';observer.observe(entry)}
 });
 return()=>{observer.disconnect();entries.forEach(entry=>delete entry.dataset.reveal)};
},[]);
const jobs=[
{date:t('now'),name:'Arctis AI',role:'founding',desc:'arctis',city:'munich',logo:'arctis.webp',href:'https://arctisai.com/'},
{date:'03 — 08 / 2025',name:t('coachOrg'),role:'coachRole',desc:'coach',city:'munich',logo:'personio-dark.svg',extraLogo:'csee.svg',extraName:'CSEE',href:'https://www.personio.com/',extraHref:'https://csee.tech/'},
{date:'04 — 09 / 2024',name:'fortiss',role:'graphRole',desc:'graph',city:'munich',logo:'fortiss.png',href:'https://www.fortiss.org/'},
{date:'08 — 10 / 2023',name:'Snowflake',role:'intern',desc:'snow',city:'berlin',logo:'snowflake-white.png',href:'https://www.snowflake.com/'},
{date:'08 / 2022 — 02 / 2023',name:'Amazon Web Services',role:'intern',desc:'aws',city:'dublin',logo:'aws-dark.svg',href:'https://aws.amazon.com/'},
{date:'03 — 04 / 2021',name:'TNG Technology Consulting',role:'tngRole',desc:'tng',city:'munich',logo:'tng.svg',href:'https://www.tngtech.com/'}
];return <>
<a className="skip" href="#main">{t('skip')}</a><div className="background"><ShaderBackground/></div>
<header id="top"><a className="wordmark" href="#top">Simon Paul</a><div className="languages" role="group" aria-label={t('language')}><Languages className="language-icon" aria-hidden="true"/>{['en','de'].map(l=><button key={l} aria-pressed={i18n.resolvedLanguage===l} onClick={()=>i18n.changeLanguage(l)}>{l.toUpperCase()}</button>)}</div></header>
<main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow hero-role"><Bot aria-hidden="true"/>{t('role')}<span className="role-divider">/</span><MapPin aria-hidden="true"/>{t('munich')}</p><h1>{t('hello')}</h1><p className="hero-tagline">{t('tagline')}</p><p className="intro">{t('intro')}</p><a className="hero-honour" href="#education"><Award aria-hidden="true"/><span><strong>{t('topClass')}</strong><small>{t('rank')}</small></span></a><div className="hero-actions"><a className="button" href={bookingUrl} target="_blank" rel="noreferrer"><span className="action-label">{t('chat')}</span><span className="action-arrow"><ArrowUpRight aria-hidden="true"/></span></a><a className="social-link" href="https://www.linkedin.com/in/simon-paul1/" target="_blank" rel="noreferrer"><span className="action-label">LinkedIn</span><span className="action-arrow"><ArrowUpRight aria-hidden="true"/></span></a></div></div><div className="portrait-wrap"><img className="portrait" src="/simon-cutout.png" alt={t('portrait')} width="1254" height="1254"/></div></section>
<div className="affiliations"><div className="company-icons"><img className="strip-arctis" src="/logos/arctis.webp" alt="Arctis AI"/><img className="strip-snowflake" src="/logos/snowflake-white.png" alt="Snowflake"/><span className="strip-aws"><img src="/logos/aws-dark.svg" alt="AWS"/></span><img className="strip-tum" src="/logos/tum.svg" alt="TUM"/></div></div>
<section className="section"><p className="eyebrow section-label"><BriefcaseBusiness aria-hidden="true"/>{t('workLabel')}</p><h2>{t('work')}</h2><div className="timeline">{jobs.map(job=><article className={`job${job.extraHref ? ' paired-job' : ''}`} key={job.name}><div className="job-meta"><span className="date">{job.date}</span><span className="job-city"><MapPin aria-hidden="true"/>{t(job.city)}</span></div><div className="job-identity"><div className={`organization-logos${job.extraLogo ? ' paired' : ''}`}><span className={`company-logo logo-${job.logo.split('.')[0]}`}>{job.href ? <a href={job.href} target="_blank" rel="noreferrer" aria-label={job.name}><img src={`/logos/${job.logo}`} alt="" aria-hidden="true"/></a> : <img src={`/logos/${job.logo}`} alt="" aria-hidden="true"/>}</span>{job.extraLogo && <span className={`company-logo companion-logo logo-${job.extraLogo.split('.')[0]}`}><img src={`/logos/${job.extraLogo}`} alt={job.extraName}/></span>}</div><div><h3>{job.name}</h3><p className="job-role">{t(job.role)}</p></div></div><p>{t(job.desc)}</p><div className="entry-links">{job.extraHref && <a href={job.extraHref} target="_blank" rel="noreferrer" aria-label={t('visit',{name:'CSEE'})} title="CSEE"><span>CSEE</span><ArrowUpRight aria-hidden="true"/></a>}<a href={job.href} target="_blank" rel="noreferrer" aria-label={t('visit',{name:job.extraHref?'Personio':job.name})} title={job.extraHref?'Personio':job.name}><span>{job.extraHref?'Personio':job.name}</span><ArrowUpRight aria-hidden="true"/></a></div></article>)}</div></section>
<section className="section education-section" id="education"><p className="eyebrow section-label"><GraduationCap aria-hidden="true"/>{t('educationLabel')}</p><div className="education-cards"><article><div className="entry-links"><a href="https://www.tum.de/" target="_blank" rel="noreferrer" aria-label={t('visit',{name:t('tum')})}><span>TUM</span><ArrowUpRight aria-hidden="true"/></a></div><img className="education-logo tum-logo" src="/logos/tum.svg" alt="" aria-hidden="true"/><div><p className="education-date">2020 — 2026 · {t('munich')}</p><h3>{t('tum')}</h3><p className="education-role">{t('tumRole')}</p><p>{t('tumText')}</p><div className="academic-highlight"><span className="rank-number">#1</span><div><strong>{t('topClass')}</strong><p>{t('rankDetail')}</p><span>{t('excellence')}</span><span>{t('scholarship')}</span></div></div></div></article><article><div className="entry-links"><a href="https://www.kth.se/" target="_blank" rel="noreferrer" aria-label={t('visit',{name:t('kth')})}><span>KTH</span><ArrowUpRight aria-hidden="true"/></a></div><img className="education-logo kth-logo" src="/logos/kth.svg" alt="" aria-hidden="true"/><div><p className="education-date">08 / 2025 — 01 / 2026 · {t('stockholm')}</p><h3>{t('kth')}</h3><p className="education-role">{t('kthRole')}</p><p>{t('kthText')}</p></div></article></div></section>
<section className="contact booking-section" id="book"><p className="eyebrow">{t('contact')}</p><h2>{t(calLink?'booking':'chat')}</h2>{calLink && <div className="calendar-embed"><BookingCalendar calLink={calLink} config={{theme:'dark',layout:'month_view',locale:i18n.resolvedLanguage??'en'}} style={{width:'100%',minHeight:620}}/></div>}<div className="booking-alternatives"><a href="mailto:mail@simon-paul.com"><Mail aria-hidden="true"/>mail@simon-paul.com</a></div></section></main><footer><span>© {new Date().getFullYear()} Simon Paul</span><span className="footer-location"><MapPin aria-hidden="true"/>{t('location')}</span><a href="#top">{t('back')}<ArrowUp aria-hidden="true"/></a></footer></>}
export default function Page(){const [instance]=useState(()=>{const i=i18next.createInstance();i.use(initReactI18next).init({resources:{en:{translation:en},de:{translation:de}},lng:'en',fallbackLng:'en',interpolation:{escapeValue:false},initImmediate:false});return i});useEffect(()=>{const detector=new LanguageDetector();detector.init(undefined,{order:['localStorage','navigator'],caches:['localStorage']});const detected=detector.detect();const list=Array.isArray(detected)?detected:[detected];const chosen=list.find(l=>l&&/^(en|de)(-|$)/i.test(l))?.slice(0,2).toLowerCase()??'en';const change=(l:string)=>{document.documentElement.lang=l;try{detector.cacheUserLanguage(l)}catch{};document.title=l==='de'?'Simon Paul — AI Engineer in München':'Simon Paul — AI Engineer'};instance.on('languageChanged',change);instance.changeLanguage(chosen);return()=>{instance.off('languageChanged',change)}},[instance]);return <I18nextProvider i18n={instance}><Profile/></I18nextProvider>}
